### ISSUE TITLE
OOM on 128G server

### ISSUE THREAD

**Issue by DreamRuthenium** [traffic-analysis/deepcoffea#5]
[1708014.228008] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1013.slice/session-1195.scope,task=python3,pid=1227971,uid=1013
[1708014.228254] Out of memory: Killed process 1227971 (python3) total-vm:184429220kB, anon-rss:120535680kB, file-rss:69120kB, shmem-rss:3072kB, UID:1013 pgtables:253596kB oom_score_adj:0
[1708019.677375] oom_reaper: reaped process 1227971 (python3), now anon-rss:1320kB, file-rss:520kB, shmem-rss:300kB

**Comment by DreamRuthenium** [comment]
Solved by shrinking the dataset into 50%, this solution would affect the performance but we can't get more RAM for now, and it works.

**Comment by yasirali0** [comment]
First of all, I would like to say this is a very valuable project in the context of correlation attacks.

I had faced the same issue as you when we started working on this project.

Luckily, I found the issue and solved it by optimizing the training code.

You can check out the optimized training code (train_fens.py) [here](https://github.com/yasirali0/fast_correlation_attack_on_tor/blob/main/train_fens.py).

This new optimized code only uses up to 70GB of RAM with the full training dataset.

**Comment by DreamRuthenium** [comment]
> First of all, I would like to say this is a very valuable project in the context of correlation attacks.
> 
> I had faced the same issue as you when we started working on this project.
> 
> Luckily, I found the issue and solved it by optimizing the training code.
> 
> You can check out the optimized training code (train_fens.py) [here](https://github.com/yasirali0/fast_correlation_attack_on_tor/blob/main/train_fens.py).
> 
> This new optimized code only uses up to 70GB of RAM with the full training dataset.

Thanks, that's a demonstration of superior coding proficiency.

**Comment by kxdkxd** [comment]
https://github.com/kxdkxd/deepcoffea_edited
In my env, pycuda does't work, if the same thing happen to you, you can try my code, the memory is within 70GB too. Refered code from [yasirali0](https://github.com/yasirali0)
